version: '3.7'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: wishlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./db_data:/var/lib/postgresql/data
